---
title: "Seminario de Tesis II"
author: "Justo Manrique Urbina - 20091107"
date: "1/5/2021"
output:
  ioslides_presentation:
      widescreen: true
      smaller: true
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
## Introducción

El objetivo de la tesis consiste en proponer un modelo de regresión cuantílica adaptado a datos con censura intervalar. Para identificar que el modelo propuesto es adecuado, aplicaremos la regresión en dos conjuntos de datos: uno simulado y otro real. La base de datos a utilizar será la Encuesta Nacional de Satisfacción de Usuarios en Salud elaborada por el Instituto Nacional de Estadística e Informática el año 2015. Los objetivos específicos de la tesis son los siguientes:

	- Revisar la literatura académica relacionada a las propuestas de modelos de regresión con 
	datos censurados intervalarmente.
	- Identificar una estructura apropiada de la distribución Weibull para el modelo de regresión cuantílica 
	vía una reparametrización del modelo.
	- Estimar los parámetros del modelo propuesto bajo inferencia clásica.
	- Implementar el método de estimación para el modelo propuesto en el lenguaje R y 
	realizar un estudio de simulación.
	- Aplicar el modelo propuesto a datos de la Encuesta Nacional de Satisfacción de Usuarios en Salud.



## Datos positivos de Censura Intervalar

\[
	Z = 
		\begin{cases}
			1, a_{1}< y < a_{2} \\
			2, a_{2} \leq Y < a_{3} \\
			3, a_{3} \leq Y < a_{4} \\
			\vdots \\
			K, a_{k} \leq Y < a_{k+1} \\
		\end{cases}
	\]

En dónde $a_1 < a_2 < \cdots <a_{k+1}$. Esto corresponde a los límites del intervalo $I$, con $a_{1}=0$ y $a_{K+1}=\infty$. La \textbf{f.d.p} de la variable observable $Z$ está definida de la siguiente forma:
	
\[P(Z=j)=P(a_{j} \leq Y < a_{j+1}) = F_Y(a_j) - F_Y(a_{j+1}) \]
	
en dónde $F_Y(\cdot)$ es la función de distribución acumulada de Y. La variable $Z$ que sigue la distribución anteriormente mencionada está denotada por 

\[Z \sim \text{Categórica}(\pi)\]

dónde $\pi=\left( \pi_{1},\dots,\pi_{k}\right)$y $\pi_{j}=P(Z=j)$.

## Sobre el proceso de censura

El mecanismo de censura de datos es el proceso que no nos permite observar directamente la variable $Y$, y solo nos da como resultado la variable categórica $Z$. Este mecanismo, dependiendo de la casuística, puede aportar información adicional a la regular. Es decir, el mecanismo de censura puede indicarnos cosas adicionales a que únicamente $y$ se encuentre en el intervalo $[a_i,a_{i+1}]$. De acuerdo a Calle y Oller, un proceso de censura no informativo considera los intervalos observados fijos e ignora su aleatoreidad. Formalmente, indica que la condición para que el proceso de censura se considere no informativo es que la distribución condicional de $a_{i}$ y $a_{i+1}$ dado $Y$ satisface lo siguiente:

\[
f_{Z|Y}(a_{i},a_{i+1}|y_{j}) = f_{Z|Y} (a_{i},a_{i+1}|y_{k}); \{(a_{i},a_{i+1}): y_{j} \in [a_{i},a_{i+1}],y_{k} \in [a_{i},a_{i+1}]\}
\]

## Verosimílitud de los datos

Bajo este contexto, y considerando las ideas plasmadas por \cite{gentleman:lmk}, el proceso de censura que deviene en la generación de la variable $Z$ es independiente del proceso generador de datos de $Y$. Por lo tanto, nuestros parámetros de interés, $q_t$ y $\alpha$ no son afectados por otro proceso. Bajo esta suposición, consideramos la verosímilitud de los datos con censura intervalar (es decir, los datos directamente observables) de la forma:

\[
	L(\theta) = \prod_{i=1}^{n} \prod_{j=1}^{k} \pi_{ij}^{\mathbb{I}(Z_{i}=j)}
\]

Considerando los resultados identificados en la ecuación \ref{eq:2}, la verosímilitud de la estructura latente de los datos es de la forma:

\[
	L(\theta) = \prod_{i=1}^{n}(F_Y(a_{j+1}) - F_Y(a_{j})) 
\]

Bajo este criterio, la verosímilitud solo depende de los valores extremos del intervalo $[a_j,a_{j+1}]$ y de la f.d.a. de la variable latente $Y$. Para hallar los puntos óptimos de la verosímilitud, utilizaremos el método de optimización de Nelder-Mead, implementado en la rutina optim del lenguaje de programación R.

## Modelo de Regresión

Considerando la reparametrización expuesta en la sección 2, el modelo de regresión cuantílica está dado por la siguiente expresión:

\[Y_{i} \sim W_{r}\left( q_{t_{i}},\alpha \right).\]
\[g\left( q_{t_{i}} \right) = x_{i}^{T}\beta.\]

\noindent en dónde $\beta=\left[ \beta_0,\beta_{1},\dots,\beta_{p} \right]^{T}$ y $x_{i}^{T} =\left[ 1,x_{i1},x_{i2},\dots,x_{ip}, \right]^{T}$. La función $g(\cdot)$ es una función de enlace estrictamente monótona y doblemente diferenciable. En el presente modelo, se utilizará la función de enlace logarítmica. El parámetro $\alpha$, el parámetro $q_{t_{i}}$ y $t$ está definido conforme la sección 2.2. La estimación de los parámetros $\beta$ y $\alpha$ se realizará mediante el método de máxima verosimilitud.



## Simulación

El proceso de simulación consiste en generar $5.000$ réplicas considerando tamaños de muestra de $n=\{100, 500, 1.000\}$. Simularemos la variable respuesta $Y_{i} \sim W_r(Q_{t_{i}},\alpha,t)$ considerando 3 covariables $X_{1i},X_{2i},X_{3i}$ que serán simuladas como:
\[X_{1i} \sim N(2,0.25)\]
\[X_{2i} \sim Beta(2,3)\]
\[X_{3i} \sim Gamma(2,20)\]

Conforme lo mencionado en la sección 3.2.1, $q_{t_{i}} =  \exp(x_i^T \beta)$, en dónde $\beta =[7, 0.3, 0.84, 2.5]^T$ y $x_{i}=(1,X_{1i},X_{2i},X_{3i})^{T}$. Por otro lado, el parámetro de dispersión tomará el valor $\alpha = 2$. Finalmente, se realizará la evaluación por los cuantiles $t = [0.1, 0.2, \dots, 0.9]$.

## Aplicación

Se utilizaron las siguientes variables, de la encuesta ENSUSALUD:

\begin{itemize}
	\itemsep0em
	\item \textbf{Características del establecimiento de salud:} (i) Tipo de institución del establecimiento.
	\item \textbf{Caracterización del profesional de salud:} (i) Profesión específica del personal de salud.
	\item \textbf{Formación académica del profesional de salud:} (i) Si el profesional cuenta con especialidad o no.
	\item \textbf{Actividad laboral del profesional de salud:} (i) Años de experiencia en el sector salud; (ii) Si el profesional realiza labor asistencial en otra institución; (iii) Si el profesional realiza labor docente remunerada; (iv) Cantidad de horas laboradas semanalmente por el profesional de salud; \textbf{(v) El ingreso mensual (censurado intervalarmente) del profesional de salud}
\end{itemize}

